### ISSUE TITLE
Stripe problem

### ISSUE THREAD

**Issue by Akshit1025** [CleverProgrammers/react-challenge-amazon-clone#25]
**Hey Clever Programmer Team**, This is `Akshit`
I started the amazon clone project and now I am having an issue with the stripe

**The issue**
I am having an issue when I am processing a payment. When I click on `Buy Now` the button becomes `processing` and then the page never responses back and then I go to stripe and it says `incomplete payment` and I am not returning to the orders page as well

**Operating System**
Windows 8.1 64-bit

**Node Version**
v14.15.1

**NPM Version**
7.19.1

> I hope you guys will help

**Error**
``` cmd
C:\Users\akshit gupta\Desktop\Coding\amazon\amazon\functions>firebase emulators:start
i  emulators: Starting emulators: functions, hosting
!  functions: The following emulators are not running, calls to these services from the
 Functions emulator will affect production: auth, firestore, database, pubsub, storage
+  functions: Using node@14 from host.
i  hosting: Serving hosting files from: build
+  hosting: Local server: http://localhost:5000
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "C:\Users\akshit gupta\Desktop\Coding\amazon\amazon\functions" f
or Cloud Functions...
i  hosting: 127.0.0.1 - - [10/Jul/2021:07:57:21 +0000] "GET / HTTP/1.1" 200 2213 "-" "M
ozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/9
1.0.4472.124 Safari/537.36"
i  hosting: 127.0.0.1 - - [10/Jul/2021:07:57:22 +0000] "GET /static/css/main.a52c1e72.c
hunk.css HTTP/1.1" 200 4741 "http://localhost:5000/" "Mozilla/5.0 (Windows NT 6.3; Win6
4; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
i  hosting: 127.0.0.1 - - [10/Jul/2021:07:57:22 +0000] "GET /static/js/main.360367af.ch
unk.js HTTP/1.1" 200 10725 "http://localhost:5000/" "Mozilla/5.0 (Windows NT 6.3; Win64
; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
i  hosting: 127.0.0.1 - - [10/Jul/2021:07:57:23 +0000] "GET /static/js/2.fd4af217.chunk
.js HTTP/1.1" 200 1129303 "http://localhost:5000/" "Mozilla/5.0 (Windows NT 6.3; Win64;
 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
i  hosting: 127.0.0.1 - - [10/Jul/2021:07:57:25 +0000] "GET /favicon.ico HTTP/1.1" 200
3870 "http://localhost:5000/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537
.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
i  hosting: 127.0.0.1 - - [10/Jul/2021:07:57:25 +0000] "GET /manifest.json HTTP/1.1" 20
0 492 "http://localhost:5000/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/53
7.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
i  hosting: 127.0.0.1 - - [10/Jul/2021:07:57:26 +0000] "GET /logo192.png HTTP/1.1" 200
5347 "http://localhost:5000/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537
.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
+  functions[us-central1-api]: http function initialized (http://localhost:5001/fir-bce
cf/us-central1/api).

┌─────────────────────────────────────────────────────────────┐
│ ?  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://localhost:4000                │
└─────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port      │ View in Emulator UI             │
├───────────┼────────────────┼─────────────────────────────────┤
│ Functions │ localhost:5001 │ http://localhost:4000/functions │
├───────────┼────────────────┼─────────────────────────────────┤
│ Hosting   │ localhost:5000 │ n/a                             │
└───────────┴────────────────┴─────────────────────────────────┘
  Emulator Hub running at localhost:4400
  Other reserved ports: 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the
 *-debug.log files.

i  functions: Beginning execution of "us-central1-api"
i  functions: Finished "us-central1-api" in ~1s
i  functions: Beginning execution of "us-central1-api"
>  Payment Request Recieved BOOM!!! for this amount >>>  9899
i  functions: Finished "us-central1-api" in ~1s
i  functions: Beginning execution of "us-central1-api"
>  Payment Request Recieved BOOM!!! for this amount >>>  0
>  (node:4008) UnhandledPromiseRejectionWarning: Error: This value must be greater than
 or equal to 1.
>      at Function.generate (C:\Users\akshit gupta\Desktop\Coding\amazon\amazon\functio
ns\node_modules\stripe\lib\Error.js:40:16)
>      at IncomingMessage.<anonymous> (C:\Users\akshit gupta\Desktop\Coding\amazon\amaz
on\functions\node_modules\stripe\lib\StripeResource.js:203:33)
>      at Object.onceWrapper (events.js:421:28)
>      at IncomingMessage.emit (events.js:327:22)
>      at endReadableNT (_stream_readable.js:1327:12)
>      at processTicksAndRejections (internal/process/task_queues.js:80:21)
>  (Use `node --trace-warnings ...` to show where the warning was created)
>  (node:4008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This erro
r originated either by throwing inside of an async function without a catch block, or b
y rejecting a promise which was not handled with .catch(). To terminate the node proces
s on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see
 https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
>  (node:4008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecate
d. In the future, promise rejections that are not handled will terminate the Node.js pr
ocess with a non-zero exit code.
i  functions: Beginning execution of "us-central1-api"
i  functions: Finished "us-central1-api" in ~1s
i  functions: Beginning execution of "us-central1-api"
>  Payment Request Recieved BOOM!!! for this amount >>>  9899
i  functions: Finished "us-central1-api" in ~1s
!  functions: Your function timed out after ~60s. To configure this timeout, see
      https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memor
y_allocation.
>  C:\Users\akshit gupta\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\f
unctionsEmulatorRuntime.js:648
>              throw new Error("Function timed out.");
>              ^
>
>  Error: Function timed out.
>      at Timeout._onTimeout (C:\Users\akshit gupta\AppData\Roaming\npm\node_modules\fi
rebase-tools\lib\emulator\functionsEmulatorRuntime.js:648:19)
>      at listOnTimeout (internal/timers.js:554:17)
>      at processTimers (internal/timers.js:497:7)
```

**Error on localhost**
![Screenshot (326)](https://user-images.githubusercontent.com/76731022/125156613-fefeaa00-e183-11eb-9635-8afc9e73a199.png)

**My payment.js code**
``` js
import React, { useState, useEffect } from 'react';
import './Payment.css';
import { useStateValue } from "./StateProvider";
import CheckoutProduct from "./CheckoutProduct";
import { Link, useHistory } from "react-router-dom";
import { CardElement, useStripe, useElements } from "@stripe/react-stripe-js";
import CurrencyFormat from "react-currency-format";
import { getBasketTotal } from "./reducer";
import axios from './axios';
import { db } from "./firebase";

function Payment() {
    const [{ basket, user }, dispatch] = useStateValue();
    const history = useHistory();

    const stripe = useStripe();
    const elements = useElements();

    const [succeeded, setSucceeded] = useState(false);
    const [processing, setProcessing] = useState("");
    const [error, setError] = useState(null);
    const [disabled, setDisabled] = useState(true);
    const [clientSecret, setClientSecret] = useState(true);

    useEffect(() => {
        // generate the special stripe secret which allows us to charge a customer
        const getClientSecret = async () => {
            const response = await axios({
                method: 'post',
                // Stripe expects the total in a currencies subunits
                url: `/payments/create?total=${getBasketTotal(basket) * 100}`
            });
            setClientSecret(response.data.clientSecret)
        }

        getClientSecret();
    }, [basket])

    console.log('THE SECRET IS >>>', clientSecret)
    console.log('👱', user)

    const handleSubmit = async (event) => {
        // do all the fancy stripe stuff...
        event.preventDefault();
        setProcessing(true);

        const payload = await stripe.confirmCardPayment(clientSecret, {
            payment_method: {
                card: elements.getElement(CardElement)
            }
        }).then(({ paymentIntent }) => {
            // paymentIntent = payment confirmation

            db
              .collection('users')
              .doc(user?.uid)
              .collection('orders')
              .doc(paymentIntent.id)
              .set({
                  basket: basket,
                  amount: paymentIntent.amount,
                  created: paymentIntent.created
              })

            setSucceeded(true);
            setError(null)
            setProcessing(false)

            dispatch({
                type: 'EMPTY_BASKET'
            })

            history.replace('/orders')
        })

    }

    const handleChange = event => {
        // Listen for changes in the CardElement
        // and display any errors as the customer types their card details
        setDisabled(event.empty);
        setError(event.error ? event.error.message : "");
    }

    return (
        <div className='payment'>
            <div className='payment__container'>
                <h1>
                    Checkout (
                        <Link to="/checkout">{basket?.length} items</Link>
                        )
                </h1>


                {/* Payment section - delivery address */}
                <div className='payment__section'>
                    <div className='payment__title'>
                        <h3>Delivery Address</h3>
                    </div>
                    <div className='payment__address'>
                        <p>{user?.email}</p>
                        <p>123 React Lane</p>
                        <p>Los Angeles, CA</p>
                    </div>
                </div>

                {/* Payment section - Review Items */}
                <div className='payment__section'>
                    <div className='payment__title'>
                        <h3>Review items and delivery</h3>
                    </div>
                    <div className='payment__items'>
                        {basket.map(item => (
                            <CheckoutProduct
                                id={item.id}
                                title={item.title}
                                image={item.image}
                                price={item.price}
                                rating={item.rating}
                            />
                        ))}
                    </div>
                </div>
            

                {/* Payment section - Payment method */}
                <div className='payment__section'>
                    <div className="payment__title">
                        <h3>Payment Method</h3>
                    </div>
                    <div className="payment__details">
                            {/* Stripe magic will go */}

                            <form onSubmit={handleSubmit}>
                                <CardElement onChange={handleChange}/>

                                <div className='payment__priceContainer'>
                                    <CurrencyFormat
                                        renderText={(value) => (
                                            <h3>Order Total: {value}</h3>
                                        )}
                                        decimalScale={2}
                                        value={getBasketTotal(basket)}
                                        displayType={"text"}
                                        thousandSeparator={true}
                                        prefix={"$"}
                                    />
                                    <button disabled={processing || disabled || succeeded}>
                                        <span>{processing ? <p>Processing</p> : "Buy Now"}</span>
                                    </button>
                                </div>

                                  {/* Errors */}
                                {error && <div>{error}</div>}
                            </form>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Payment;
```

**Comment by TitirBiswas** [comment]
I'm facing the same problem , please help out

**Comment by Akshit1025** [comment]
I have stopped this project as I don't have a blaze plan for the functions

Sorry!!

**Comment by GourabSanyal** [comment]
> I'm facing the same problem , please help out



> I have stopped this project as I don't have a blaze plan for the functions
> 
> Sorry!!


I have given a solution for this error, you can check it out here:

https://github.com/CleverProgrammers/react-challenge-amazon-clone/issues/28
